package com.fortunatehtml.android.network

import com.fortunatehtml.android.data.db.dao.TrafficEntryDao
import com.fortunatehtml.android.data.db.entity.TrafficEntryEntity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import okhttp3.Interceptor
import okhttp3.Response
import okio.Buffer

/**
 * OkHttp application-layer interceptor that records first-party HTTP traffic
 * generated by THIS app into the local database.
 *
 * This interceptor only captures requests made by OkHttp clients within this
 * application (i.e. the Repeater feature). It does NOT intercept traffic from
 * other apps, system traffic, or perform any TLS manipulation.
 *
 * Usage:
 *   val client = OkHttpClient.Builder()
 *       .addInterceptor(OkHttpInspector(trafficDao))
 *       .build()
 */
class OkHttpInspector(
    private val trafficDao: TrafficEntryDao,
    private val scope: CoroutineScope = CoroutineScope(Dispatchers.IO)
) : Interceptor {

    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val startTime = System.currentTimeMillis()

        // Capture request body (buffered copy so the real body is not consumed)
        val requestBodyStr = runCatching {
            val buffer = Buffer()
            request.body?.writeTo(buffer)
            buffer.readUtf8()
        }.getOrNull()

        val entry = TrafficEntryEntity(
            method          = request.method,
            url             = request.url.toString(),
            host            = request.url.host,
            path            = request.url.encodedPath,
            scheme          = request.url.scheme,
            queryParams     = request.url.encodedQuery ?: "",
            requestHeaders  = request.headers.toMap(),
            requestBody     = requestBodyStr,
            isHttps         = request.url.scheme == "https",
            source          = "okhttp",
            state           = "PENDING"
        )

        // Insert the pending entry for early visibility in the UI.
        // OnConflictStrategy.REPLACE on the DAO means subsequent inserts with the
        // same primary key (entry.id) act as upserts – no race condition risk.
        scope.launch { trafficDao.insert(entry) }

        // Execute the request
        val response: Response
        val duration: Long
        try {
            response = chain.proceed(request)
            duration = System.currentTimeMillis() - startTime
        } catch (e: Exception) {
            // Replace the PENDING row with a FAILED one using the same id.
            scope.launch { trafficDao.insert(entry.copy(state = "FAILED")) }
            throw e
        }

        // Capture response body (peek without consuming)
        val responseBodyStr = runCatching {
            response.peekBody(Long.MAX_VALUE).string()
        }.getOrNull()

        val responseSize = responseBodyStr?.length?.toLong()

        // Replace the PENDING row with the completed entry (same id → upsert).
        scope.launch {
            trafficDao.insert(
                entry.copy(
                    statusCode      = response.code,
                    responseHeaders = response.headers.toMap(),
                    responseBody    = responseBodyStr,
                    duration        = duration,
                    responseSize    = responseSize,
                    contentType     = response.header("Content-Type"),
                    state           = "COMPLETE"
                )
            )
        }

        return response
    }

    /** Convert OkHttp Headers to a plain map. */
    private fun okhttp3.Headers.toMap(): Map<String, String> =
        (0 until size).associate { name(it) to value(it) }
}
